// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    Posts: typeof import('./components/Posts.vue')['default']
    PostsList: typeof import('./components/Posts.vue')['default']
    User: typeof import('./components/User.vue')['default']
    Users: typeof import('./components/Users.vue')['default']
  }
}

export { }
